//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarRealms
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveFiles
    {
        public int Id { get; set; }
        public string SaveFilePath { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
